
;/*=========== USA Vehicles Begin ===========*/

(define "m4_sound"
	{on "add_movement_sound" overload
		{link_sound "engine_start"		"vehicle/engine/m4/start"}
		{link_sound "engine_stop"		"vehicle/engine/m4/stop"}
		{link_sound "engine_idle"		"vehicle/engine/m4/idle"}
		{link_sound "engine_full"		"vehicle/engine/m4/full"}
		{link_sound "exhaust"			"vehicle/engine/m4/exhaust"}
		{link_sound "move"			"vehicle/tracks/m4"}
		{link_sound "rotate_turret"		"vehicle/turret/electric/electric_light"}
	}
)
(define "m4a2_sound"
	{on "add_movement_sound" overload
		{link_sound "engine_start"		"vehicle/engine/m4a2/start"}
		{link_sound "engine_stop"		"vehicle/engine/m4a2/stop"}
		{link_sound "engine_idle"		"vehicle/engine/m4a2/idle"}
		{link_sound "engine_full"		"vehicle/engine/m4a2/full"}
		{link_sound "exhaust"			"vehicle/engine/m4a2/exhaust"}
		{link_sound "move"			"vehicle/tracks/m4"}
		{link_sound "rotate_turret"		"vehicle/turret/electric/electric_light"}
	}
)
(define "m4a3_sound"
	{on "add_movement_sound" overload
		{link_sound "engine_start"		"vehicle/engine/m4a3/start"}
		{link_sound "engine_stop"		"vehicle/engine/m4a3/stop"}
		{link_sound "engine_idle"		"vehicle/engine/m4a3/idle"}
		{link_sound "engine_full"		"vehicle/engine/m4a3/full"}
		{link_sound "exhaust"			"vehicle/engine/m4a3/exhaust"}
		{link_sound "move"			"vehicle/tracks/m4a2"}
		{link_sound "rotate_turret"		"vehicle/turret/electric/electric_light"}
	}
)
(define "m3lee_sound"
	{on "add_movement_sound" overload
		{link_sound "engine_start"		"vehicle/engine/m3lee/start"}
		{link_sound "engine_stop"		"vehicle/engine/m3lee/stop"}
		{link_sound "engine_idle"		"vehicle/engine/m3lee/idle"}
		{link_sound "engine_full"		"vehicle/engine/m3lee/full"}
		{link_sound "exhaust"			"vehicle/engine/m3lee/exhaust"}
		{link_sound "move"			"vehicle/tracks/m7"}
		{link_sound "rotate_turret"		"vehicle/turret/electric/electric_light"}
	}
)
(define "m7_sound"
	{on "add_movement_sound" overload
		{link_sound "engine_start"		"vehicle/engine/m3lee/start"}
		{link_sound "engine_stop"		"vehicle/engine/m3lee/stop"}
		{link_sound "engine_idle"		"vehicle/engine/m3lee/idle"}
		{link_sound "engine_full"		"vehicle/engine/m3lee/full"}
		{link_sound "exhaust"			"vehicle/engine/m3lee/exhaust"}
		{link_sound "move"			"vehicle/tracks/m7"}
		{link_sound "rotate_turret" 		"vehicle/turret/gun/gun_horizontal"}
		{link_sound "rotate_gun" 		"vehicle/turret/gun/gun_vertical"}
	}
)
(define "m3stuart_sound"
	{on "add_movement_sound" overload
		{link_sound "engine_start"		"vehicle/engine/m3stuart/start"}
		{link_sound "engine_stop"		"vehicle/engine/m3stuart/stop"}
		{link_sound "engine_idle"		"vehicle/engine/m3stuart/idle"}
		{link_sound "engine_full"		"vehicle/engine/m3stuart/full"}
		{link_sound "exhaust"			"vehicle/engine/m3stuart/exhaust"}
		{link_sound "move"			"vehicle/tracks/m3a1_stuart"}
		{link_sound "rotate_turret"		"vehicle/turret/handcrank/handcrank_light"}
	}
)
(define "m24_sound"
	{on "add_movement_sound" overload
		{link_sound "engine_start"		"vehicle/engine/m24/start"}
		{link_sound "engine_stop"		"vehicle/engine/m24/stop"}
		{link_sound "engine_idle"		"vehicle/engine/m24/idle"}
		{link_sound "engine_full"		"vehicle/engine/m24/full"}
		{link_sound "exhaust"			"vehicle/engine/m24/exhaust"}
		{link_sound "move"			"vehicle/tracks/m24"}
		{link_sound "rotate_turret"		"vehicle/turret/electric/electric_light"}
	}
)
(define "m26_sound"
	{on "add_movement_sound" overload
		{link_sound "engine_start"		"vehicle/engine/m26/start"}
		{link_sound "engine_stop"		"vehicle/engine/m26/stop"}
		{link_sound "engine_idle"		"vehicle/engine/m26/idle"}
		{link_sound "engine_full"		"vehicle/engine/m26/full"}
		{link_sound "exhaust"			"vehicle/engine/m26/exhaust"}
		{link_sound "move"			"vehicle/tracks/m26"}
		{link_sound "rotate_turret"		"vehicle/turret/hydraulic/hydraulic_heavy"}
	}
)
(define "us_halftrack_sound"
	{on "add_movement_sound" overload
		{link_sound "engine_start"		"vehicle/engine/us_halftrack/start"}
		{link_sound "engine_stop"		"vehicle/engine/us_halftrack/stop"}
		{link_sound "engine_idle"		"vehicle/engine/us_halftrack/idle"}
		{link_sound "engine_full"		"vehicle/engine/us_halftrack/full"}
		{link_sound "exhaust"			"vehicle/engine/us_halftrack/exhaust"}
		{link_sound "move"			"vehicle/tracks/m3a1"}
		{link_sound "rotate_turret" 		"vehicle/turret/gun/gun_horizontal"}
		{link_sound "rotate_gun" 		"vehicle/turret/gun/gun_vertical"}
	}
)
(define "m8grayhound_sound"
	{on "add_movement_sound" overload
		{link_sound "engine_start"		"vehicle/engine/m8grayhound/start"}
		{link_sound "engine_stop"		"vehicle/engine/m8grayhound/stop"}
		{link_sound "engine_idle"		"vehicle/engine/m8grayhound/idle"}
		{link_sound "engine_full"		"vehicle/engine/m8grayhound/full"}
		{link_sound "exhaust"			"vehicle/engine/m8grayhound/exhaust"}
		{link_sound "move"			"vehicle/wheels/truck"}
		{link_sound "brake"			"vehicle/wheels/brake"}
		{link_sound "rotate_turret"		"vehicle/turret/handcrank/handcrank_light"}

		{link_sound "wheel_ground"  	"vehicle/wheels/overlay/wheel_overlay_ground"}
		{link_sound "wheel_sand"		"vehicle/wheels/overlay/wheel_overlay_ground"}
		{link_sound "wheel_grass" 		"vehicle/wheels/overlay/wheel_overlay_ground"}
		{link_sound "wheel_water" 		"vehicle/wheels/overlay/wheel_overlay_water"}
		{link_sound "wheel_puddle" 		"vehicle/wheels/overlay/wheel_overlay_water"}
		{link_sound "wheel_mud" 		"vehicle/wheels/overlay/wheel_overlay_mud_snow"}
		{link_sound "wheel_snow" 		"vehicle/wheels/overlay/wheel_overlay_mud_snow"}
		{link_sound "wheel_road" 		"vehicle/wheels/overlay/wheel_overlay_road"}
		{link_sound "wheel_rock" 		"vehicle/wheels/overlay/wheel_overlay_rock"}
		{link_sound "wheel_wood" 		"vehicle/wheels/overlay/wheel_overlay_wood"}
	}
)
(define "m10_sound"
	{on "add_movement_sound" overload
		{link_sound "engine_start"		"vehicle/engine/m4/start"}
		{link_sound "engine_stop"		"vehicle/engine/m4/stop"}
		{link_sound "engine_idle"		"vehicle/engine/m4/idle"}
		{link_sound "engine_full"		"vehicle/engine/m4/full"}
		{link_sound "exhaust"			"vehicle/engine/m4/exhaust"}
		{link_sound "move"			"vehicle/tracks/m4"}
		{link_sound "rotate_turret" 		"vehicle/turret/gun/gun_horizontal"}
		{link_sound "rotate_gun" 		"vehicle/turret/gun/gun_vertical"}
	}
)
(define "m5hst_sound"
	{on "add_movement_sound" overload
		{link_sound "engine_start"		"vehicle/engine/m3stuart/start"}
		{link_sound "engine_stop"		"vehicle/engine/m3stuart/stop"}
		{link_sound "engine_idle"		"vehicle/engine/m3stuart/idle"}
		{link_sound "engine_full"		"vehicle/engine/m3stuart/full"}
		{link_sound "exhaust"			"vehicle/engine/m3stuart/exhaust"}
		{link_sound "move"			"vehicle/tracks/m3a1_stuart"}
		{link_sound "rotate_turret"		"vehicle/turret/handcrank/handcrank_light"}
	}
)
{"m3a1_scout tank" 
	("m8grayhound_sound")
}
{"m20 tank" 
	("m8grayhound_sound")
}
{"m8_grayhound tank" 
	("m8grayhound_sound")
}
{"t30hmc tank" 
	("us_halftrack_sound")
}
{"t12gmc tank" 
	("us_halftrack_sound")
}
{"m15a1 tank" 
	("us_halftrack_sound")
}
{"m22 tank" 
	("m3stuart_sound")
}
{"m3_stuart tank" 
	("m3stuart_sound")
}
{"m3_satan" 
	("m3stuart_sound")
	{on spawn
		{add_view "flamer_fire_tank" "flame" "foresight1"}
		{add_view "flamer_fire_barrel" "fire" "foresight1"}
	}
	{on operatable on
		{view start "fire"}
	}
	{on operatable off
		{view stop "fire"}
	}
	{on "_explosion"
		{spawn "fuel_die"}
		{blastwave c4 5 r0 4 r1 15}
		{fire radius 5 time 15 heating 10}
	}
	("flame_weapon" args gun 60 1 40)
}
{"m5a1 tank"
	("m3stuart_sound")
}
{"m8 tank"
	("m3stuart_sound")
}
{"m3lee tank"
	("m3lee_sound")
}
{"m4a1 tank"
	("m4_sound")
}
{"m4 tank"	
	("m4_sound")
	{on "commander_hatch_open" overload
		{ani_wind "open" end}
	}
	{on "commander_hatch_close" overload
		{ani_play "open" -1.0 resume}
	}	
}	
{"m10wolverine tank"
	("m10_sound")
	{on "gunner2_hatch_open" overload
		{ani_play "open" -1.0 resume}
	}
}
{"m7 tank"
	("m7_sound")
}
{"m4a3c tank"
	("m4a3_sound")
}
{"m4a3_zippo tank"
	("m4a3_sound")
	{on spawn
		{add_view "flamer_fire_tank" "flame" "foresight5"}
		{add_view "flamer_fire_barrel" "fire" "foresight5"}
	}
	{on operatable on
		{view start "fire"}
	}
	{on operatable off
		{view stop "fire"}
	}
	{on "_explosion"
		{spawn "fuel_die"}
		{blastwave c4 5 r0 4 r1 15}
		{fire radius 5 time 15 heating 10}
	}
	("flame_weapon" args flamer1 60 1 40)
	{on "commander_hatch_open" overload
		{ani_wind "open" end}
	}
	{on "commander_hatch_close" overload
		{ani_play "open" -1.0 resume}
	}
}
{"m12gmc tank"
	("m3lee_sound")
}
{"m4a3_105 tank"
	("m4a3_sound")
	{on "commander_hatch_open" overload
		{ani_wind "open" end}
	}
	{on "commander_hatch_close" overload
		{ani_play "open" -1.0 resume}
	}
}
{"m4a3e2_jumbo_76w tank"
	("m4a3_sound")
	{on "commander_hatch_open" overload
		{ani_wind "open" end}
	}
	{on "commander_hatch_close" overload
		{ani_play "open" -1.0 resume}
	}
}
{"m4a3e2_jumbo tank"
	("m4a3_sound")
	{on "commander_hatch_open" overload
		{ani_wind "open" end}
	}
	{on "commander_hatch_close" overload
		{ani_play "open" -1.0 resume}
	}
}
{"m4a3_75 tank"
	("m4a3_sound")
	{on "commander_hatch_open" overload
		{ani_wind "open" end}
	}
	{on "commander_hatch_close" overload
		{ani_play "open" -1.0 resume}
	}
}
{"m26_pershing tank"
	("m26_sound")
	{on "commander_hatch_open" overload
		{ani_wind "open" end}
	}
	{on "commander_hatch_close" overload
		{ani_play "open" -1.0 resume}
	}
}
{"m26e4_pershing tank"
	("m26_sound")
	{on "commander_hatch_open" overload
		{ani_wind "open" end}
	}
	{on "commander_hatch_close" overload
		{ani_play "open" -1.0 resume}
	}
}
{"m18 tank"
	("m24_sound")
}
{"m24_chaffee tank"
	("m24_sound")
}
{"m3_usa tank"
	("us_halftrack_sound")
}
{"m36gmc tank"
	("m10_sound")
	{on "gunner2_hatch_open" overload
		{ani_play "open" -1.0 resume}
	}
}
{"m36b1 tank"
	("m4a3_sound")
}
{"m4a3e8 tank"
	("m4a3_sound")
	{on "commander_hatch_open" overload
		{ani_wind "open" end}
	}
	{on "commander_hatch_close" overload
		{ani_play "open" -1.0 resume}
	}
}
{"m4a1e8 tank"	
	("m4_sound")
	{on "commander_hatch_open" overload
		{ani_wind "open" end}
	}
	{on "commander_hatch_close" overload
		{ani_play "open" -1.0 resume}
	}	
}	
{"m2halftrack"
	("us_halftrack_sound")
}
{"m2a4"
	{on "init_gun"
		{add_view	"flash_gun_big"	"flashbarrel3"	"Foresight3"}
		{add_view	"flash_gun_big"	"flashbarrel4"	"Foresight4"}
		{add_view	"flash_gun_big"	"flashbarrel5"	"Foresight5"}
		{add_view	"flash_gun_big"	"flashbarrel6"	"Foresight6"}
		{add_view	"flash_gun_big"	"flashbarrel7"	"Foresight7"}
		{add_view	"flash_gun_big"	"flashbarrel3"	"Foresight14"}
		{link_sound "bkg"	"weapon/shot/bkg/gun/mg"}
	}
	("m3stuart_sound")
	("on_fire_mgun" args mgun4 flashbarrel7)
}
{"m16 tank" 
	("us_halftrack_sound")
	{on spawn
		{link_sound "bkg_hmg" "weapon/shot/bkg/gun/hmg/"}
		{add_view "flash_gun_hmg_dshk"			"flashbarrel00"	"shooter00"}
		{add_view "flash_gun_hmg_dshk"			"flashbarrel01"	"shooter01"}
		{add_view "flash_gun_hmg_dshk"			"flashbarrel02"	"shooter02"}
		{add_view "flash_gun_hmg_dshk"			"flashbarrel03"	"shooter03"}
		{add_view "zenit_gilz"			"shell"			"FXshell1"}
		{add_view "zenit_gilz"			"shell"			"FXshell2"}
		{add_view "zenit_gilz"			"shell"			"FXshell3"}
		{add_view "zenit_gilz"			"shell"			"FXshell4"}
	}
	{on fire "mgun1" overload
		(define "fire_barrel"
			name "%0"
				{call "fire_barrel%0"}
				{view start "flashbarrel%0"}
				{ani_play "fire%0"}
				{delay 0.2
					{view pause "flashbarrel%0"}
				}
		)
		{if	("fire_barrel" args 00)
		else ("fire_barrel" args 01)
		else ("fire_barrel" args 02)
		else ("fire_barrel" args 03)
		}
		{play_sound "bkg_hmg"}
		{ani_play "recoil"}
		{call "spawn_shell"}
	}
}
{"m4a1_76 tank"
	("m4_sound")
	{on "commander_hatch_open" overload
		{ani_wind "open" end}
	}
	{on "commander_hatch_close" overload
		{ani_play "open" -1.0 resume}
	}	
}	

{"m4hst"
	("m5hst_sound")
}
{"m10wolverine_eng tank"
	("m10_sound")
	{on "gunner2_hatch_open" overload
		{ani_play "open" -1.0 resume}
	}		
}
{"m3lee_eng tank"
	("m3lee_sound")
}
{"m3a1_scout_eng tank" 
	("m8grayhound_sound")
}
{"lvt4"
	("m3stuart_sound")
}
{"m3grant tank"
	("m3lee_sound")
}
{"lvt4_wb2"
	("m3stuart_sound")
}
{"t26e4 tank"
	("m26_sound")
	{on "commander_hatch_open" overload
		{ani_wind "open" end}
	}
	{on "commander_hatch_close" overload
		{ani_play "open" -1.0 resume}
	}
}
{"m4a1_76_w tank"
	("m4_sound")
	{on "commander_hatch_open" overload
		{ani_wind "open" end}
	}
	{on "commander_hatch_close" overload
		{ani_play "open" -1.0 resume}
	}	
}
{"m4a3e8_fury tank"
	("m4_sound")
	{on "commander_hatch_open" overload
		{ani_wind "open" end}
	}
	{on "commander_hatch_close" overload
		{ani_play "open" -1.0 resume}
	}	
}
{"m18_90 tank"
	("m24_sound")
}
{"t29 tank"
	("m26_sound")
	{on "commander_hatch_open" overload
		{ani_wind "open" end}
	}
	{on "commander_hatch_close" overload
		{ani_play "open" -1.0 resume}
	}
}
{"m7_eng tank"
	("m7_sound")
}
{"m3a1_scout_tr tank" 
	("m8grayhound_sound")
}
{"t26e2 tank"
	("m26_sound")
	{on "commander_hatch_open" overload
		{ani_wind "open" end}
	}
	{on "commander_hatch_close" overload
		{ani_play "open" -1.0 resume}
	}
}
;(include "tank-extra.inc")
;/*=========== USA Vehicles End ===========*/